version: "3.9"
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - mysql:/var/lib/mysql
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  users:
    build: ./users/
    image: deliagherghe/users:latest
    container_name: users
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb
      - zipkin
      - prometheus
    restart: on-failure
  movies:
    build: ./movies/
    image: deliagherghe/movies:latest
    container_name: movies
    ports:
      - "8001:8001"
    depends_on:
      - mysqldb
      - zipkin
      - prometheus
    restart: on-failure
  ratings_reviews:
    build: ./ratings_reviews/
    image: deliagherghe/ratings_reviews:latest
    container_name: ratings_reviews
    ports:
      - "8002:8002"
    depends_on:
      - mysqldb
      - zipkin
      - prometheus
    restart: on-failure
  watchlists:
    build: ./watchlists/
    image: deliagherghe/watchlists:latest
    container_name: watchlists
    ports:
      - "8003:8003"
    depends_on:
      - mysqldb
      - zipkin
      - prometheus
    restart: on-failure
volumes:
  mysql: